fint:
  flyt:
    resource-server:
      security:
        api:
          internal-client:
            enabled: true
            authorized-client-ids: ${fint.sso.client-id}
  application-id: fint-flyt-kafka-test-service
server:
  error:
    include-message: always
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-resource-server